force-app/main/default/objects/Questionnaire__c/Questionnaire__c.object-meta.xml
<CustomObject>
    <description>Contains multiple questions and answers</description>
    <label>Questionnaire</label>
    <nameField>
        <label>Questionnaire Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questionnaires</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Questionnaire_Question__c/Questionnaire_Question__c.object-meta.xml
<CustomObject>
    <description>Relates to a Questionnaire and can have Answers added.</description>
    <label>Questionnaire - Question</label>
    <nameField>
        <label>Question</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questionnaire - Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

01. initial code/main/questionnaires/objects/Questionnaire_Question__c/fields/Questionnaire__c.field-meta.xml
<CustomField>
    <fullName>Questionnaire__c</fullName>
    <label>Questionnaire</label>
    <referenceTo>Questionnaire__c</referenceTo>
    <relationshipName>Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

04. Completed Solution/main/questionnaires/objects/Questionnaire_Question__c/fields/QuestionNumber__c.field-meta.xml
<CustomField>
    <fullName>QuestionNumber__c</fullName>
    <label>Question_Number</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/populateSampleQuestionnaireRecords.cls
public class populateSampleQuestionnaireRecords {
	public static void initData() {

		// SELECT Id, Description__c, Name, (SELECT QuestionNumber__c, Questionnaire__c, Name, Id FROM Questions__r) FROM Questionnaire__c

		Questionnaire__c q1 = new Questionnaire__c(
			Name = 'October Experience Feedback',
			Description__c = 'Please give feedback on the Company Night held on October 31st - was it spooky enough for you?'
		);

		insert q1;

		List<Questionnaire_Question__c> questions = new List<Questionnaire_Question__c>();

		questions.add(
			new Questionnaire_Question__c(
				Questionnaire__c = q1.id,
				QuestionNumber__c = 4,
				Name = 'The entertainment was a good choice'
			)
		);


		questions.add(
			new Questionnaire_Question__c(
				Questionnaire__c = q1.id,
				QuestionNumber__c = 3,
				Name = 'The food and drink was very good'
			)
		);

		questions.add(
			new Questionnaire_Question__c(
				Questionnaire__c = q1.id,
				QuestionNumber__c = 2,
				Name = 'I was able to find an appropriate costume'
			)
		);

		questions.add(
			new Questionnaire_Question__c(
				Questionnaire__c = q1.id,
				QuestionNumber__c = 5,
				Name = 'I look forward to next years party'
			)
		);


		questions.add(
			new Questionnaire_Question__c(
				Questionnaire__c = q1.id,
				QuestionNumber__c = 1,
				Name = 'The Decorations scared me.'
			)
		);


		Questionnaire__c q2 = new Questionnaire__c(
			Name = 'Salesforce Course Questionnaire',
			Description__c = 'Your feedback is very much appreciated'
		);

		insert q2;


		questions.add(
			new Questionnaire_Question__c(
				Questionnaire__c = q2.id,
				QuestionNumber__c = 1,
				Name = 'The facilitator was knowledgable.'
			)
		);

		questions.add(
			new Questionnaire_Question__c(
				Questionnaire__c = q2.id,
				QuestionNumber__c = 1,
				Name = 'The course material was of interest to me.'
			)
		);

		questions.add(
			new Questionnaire_Question__c(
				Questionnaire__c = q2.id,
				QuestionNumber__c = 1,
				Name = 'The Course will be useful in my day-to-day tasks.'
			)
		);


		questions.add(
			new Questionnaire_Question__c(
				Questionnaire__c = q2.id,
				QuestionNumber__c = 1,
				Name = 'The course material was engaging.'
			)
		);




		Questionnaire__c q3 = new Questionnaire__c(
			Name = 'General Feedback Survey',
			Description__c = 'General Survey'
		);

		insert q3;


		questions.add(
			new Questionnaire_Question__c(
				Questionnaire__c = q3.id,
				QuestionNumber__c = 1,
				Name = 'The food and refreshments were excellent.'
			)
		);



		questions.add(
			new Questionnaire_Question__c(
				Questionnaire__c = q3.id,
				QuestionNumber__c = 2,
				Name = 'The directions provided for the day were helpful.'
			)
		);



		questions.add(
			new Questionnaire_Question__c(
				Questionnaire__c = q3.id,
				QuestionNumber__c = 3,
				Name = 'The location was ideal for the event.'
			)
		);

		insert questions;

		
	}
}